project_name: gosl

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...

builds:
  - skip: true

release:
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  discussion_category_name: General
  prerelease: auto
  mode: replace
  header: |
    ## ⚙️ The `{{ .Tag }}` release
  footer: |
    ## Install or update
    
    ```console
    go get -u github.com/koddr/gosl
    ```
    
    > 💡 Note: Basic usage and full code examples of all functions of the `gosl` package, you can find on the [pkg.go.dev][go_dev_url] page.
    
    ## Your help to improve project
    
    I'd be truly grateful for help with:
    
    - Creating a new Go snippets (with tests & benchmarks)
    - Improve an existing Go snippets, tests, or benchmarks
    - Feature requests with interesting snippets that make life easier when writing Go programs that would be good to add
    
    Your PRs & issues are welcome! Thanks 😉
    
    [go_dev_url]: https://pkg.go.dev/github.com/koddr/gosl
  disable: false
  skip_upload: true

changelog:
  use: git
  sort: asc
  abbrev: -1
  filters:
    exclude: [ "^*.md:", "^*.yml:" ]
  groups:
    - title: Features
      regexp: ^.*?(F|f)eature.*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Others
      order: 999
