name: Linter & Scanner

on:
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    strategy:
      matrix:
        go: [ 'stable' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run go-critic linter
        run: go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...
      - name: Run gosec scanner
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
